version: '3.8'

services:
  betting-service:
    build:
      context: /var/www/betting-service
      dockerfile: Dockerfile
    container_name: betting-service
    hostname: betting-service
    networks:
      - sbenet
    ports:
      - 9000:80
      - 9001:5000
    expose:
      - 80
      - 5000
    environment:
      DB_TYPE: mysql
      DB_HOST: betrader-database-do-user-11619495-0.b.db.ondigitalocean.com
      DB_PORT: 25060
      DB_PASSWORD: AVNS_QzyFKDS7oT4Rcy541Px
      DB_USERNAME: betting_service
      DB_NAME: betting_service
      SYSTEM_PORT: 80
      SYSTEM_HOST: 0.0.0.0
      DEBUG: 1
      RABITTMQ_URI: amqp://bs:betting@137.184.222.24:5672/sportsbook
      FEEDS_SERVICE_GRPC_URI: 161.35.104.145:6011

    deploy:
      restart_policy:
        condition: on-failure
networks:
  sbenet:
    driver: bridge